jupyterlab/jupyterlab-google-drive

README.md

The JupyterLab team rocks. :cake: 🍦 :tada:

Add getting started to README. Woo hoo!

---

src/drive/drive.ts

documents in the root directory.

Check for '.' from dirname, which was not allowing creating new

---

advanced.md
src/drive/browser.ts
src/drive/drive.ts
src/gapi.ts
src/index.ts
style/index.css

Add Client ID to settings

---

.travis.yml

Skirts around a problem with an old gcc in the older Ubuntu 12.04 Travis images.

Travis fix.

---

src/index.ts

Performs some email address validation, plus allowing for multiple email address entry upon sharing.
Addresses #9. I have not included `';'` as an address separator, as I have tried to follow the HTML spec given here: https://html.spec.whatwg.org/multipage/input.html#e-mail-state-(type=email)

Perform some email address validation

---

.travis.yml
src/chatbox/chatbox.ts
src/chatbox/entry.ts
src/chatbox/panel.ts
src/drive/browser.ts
src/drive/contents.ts
src/drive/drive.ts
src/gapi.ts
src/index.ts
src/realtime/collaborator.ts
src/realtime/json.ts
src/realtime/list.ts
src/realtime/map.ts
src/realtime/modeldb.ts
src/realtime/string.ts
src/realtime/undoablelist.ts
test/src/chatbox.spec.ts
tsconfig.json

This updates the code so that it will pass `strictNullChecks` in the typescript compiler.

Updates for `strictNullChecks`

---

src/drive/drive.ts
src/index.ts

* Use the new interface for the sharing dialog.
* Batches multiple email permissions requests into a single request.

Sharing updates

---

src/drive/drive.ts

Nested shared directories were failing to reload on refresh, due to a bug in the Google Drive directory traversal. This fixes that.

Fix directory walking within `Shared With Me`.

---

.travis.yml
src/drive/browser.ts
src/drive/contents.ts
src/drive/drive.ts
src/drive/gapi.client.drive.d.ts
src/gapi.ts
src/index.ts

Adds typings for a bunch of things in the Google Drive client APIs that had been untyped.  This is still not perfect, as parts of the API are underdocumented, and I have had to make some adjustments, but it is better than nothing.

Drive typings

---

src/drive/drive.ts
src/gapi.ts

Some recent commits broke image upload/download again. This reverts those changes.

Fix image download/upload (again!)

---

src/drive/contents.ts
src/drive/drive.ts
src/index.ts

Addresses #47, at least as a first pass.

Support team drives

---

package.json

Addresses an error reported by @pgreisen.

Add phosphor dragrdop to package.json

---

src/gapi.ts

Retry a request using exponential backoff upon backend error.

---

docs/troubleshooting.md

Doc improvements 2

---

package.json
src/gapi.ts

JQuery is largely unnecessary in this package. Rewrite the one place it is used to use pure JS/DOM.

Remove jquery

---

.travis.yml

cf https://github.com/jupyterlab/jupyterlab/pull/2958

Make travis build slightly less brittle.

---

src/drive/drive.ts

Don't assume that the root drive is named 'My Drive' for internationalization purposes.

---

style/chatbox.css

Modified from refinements due to @cameronoelsen.

Chat refinements

---

src/index.ts

This improves the chatbox's ability to track currently open collaborative documents.
1. If the current widget shifts focus, it checks to see if it is a collaborative document. If so, that becomes the currently active chatbox. If not the currently active chatbox remains the same.
2. If a context is closed, it checks if that was the active context for the chatbox. If not, it does nothing. If it was, it looks for a new open collaborative context.
3. If when iterating over the currently active widgets to find a new collaborative context it cannot find one, it removes the chatbox panel from the left area.

Improve tracking of open collaborative documents for chatbox.

---

src/gapi.ts

Attempt to refresh auth token on 401 error.

---

docs/advanced.md

closes #98 
@ian-r-rose ... see if this is any use.

extend docs to discuss pre-seeding clientId credentials

---

package.json
src/index.ts

Adds `Share` to the `File` menu.

Share in menu

---

README.md

Add a note about the "unverified" warning.

---

src/realtime/modeldb.ts

Make a copy of objects coming out of the realtime API so they may be

---

package.json

Adds the keyword "jupyterlab extension" for eased discoverability.

Add package metadata for discoverability

---

src/browser.ts
src/contents.ts
src/drive.ts
src/gapi.ts
src/index.ts
test/src/contents.spec.ts
test/src/util.ts

Use async/await instead of deeply chained promises in a lot of the codebase. Should be a no-op, despite the large line diff.

Async await

---

README.md

Minor nitpicks and grammaticals

DOC: README.md: syntax
